language: node_js

node_js:
  - "4"
  - "6"

matrix:
  allow_failures:
   - node_js: "6"

notifications:
  slack:
    rooms:
    - secure: "tu+hrWqnLkYXBRrkHZIFBl1VFtswDU9CQ2OyGq8pa4a6DcLePODNup3bblCsAJEB80YIgffpjNyRWXCitp6OudrNgYvdm11fj/sEqdYUQN6z2eXi/avhFyrmOmFR1jZFdphGZCVVQOxtTecNN5JasuTDLRn8FshCcChThUWkIVd2Df0/VX6aetrdvNdyikXPyyqT4qTNWSe5EthtaHbHMAP2A3rxYItxLM1TMRYERDKPxGdZ3naHIGPbG3wPc7WVhOZCmTMM0kWdVHYOAH3a3/SMM/B+MJkPaHk8hsyeCEc+BMsyBFGLSYbXHqEmfot1dZmFAdaQecyYO+FEevT71wYfUan9pcoO/M/CsF0a1TdWONqxmJe/N8vk9T0RMpBzEbx74zeA/PC45XhEFT150IMRr25Uzs80k3DMsNKoD8Bho+ibD1AAZvg15DYinrunKiuyZHYxBd+cnAYfzAZcYN0KbfSc0GufWpEKyGMbg5pec7qq14u4mTT4BNIRB2ivUpv8GxtUs0Q/YVoMOtXOP9WQOtXCSOl0uO8teVI3rzRlztBtOSAQiSTkdptCOh1n/XI7CbIplpYDsT5YWxpoToV1wIrNUwOdSwWAcy+FW4YvDHKu4VMs1XzdVGLv+XP35LSHeKi8HCHhdWNa7LNu/t1u0H5wmkB9M3DFeeTc07c="
    on_success: never
    on_failure: always
    on_start: never
    on_pull_requests: false
